/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class demo_DemoJni */

#ifndef _Included_demo_DemoJni
#define _Included_demo_DemoJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     demo_DemoJni
 * Method:    sayHello
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_demo_DemoJni_sayHello
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
